/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MapProfile, MapId } from '../types';

export const MAP_PROFILES: Record<MapId, MapProfile> = {
  COUNTRYSIDE: {
    id: 'COUNTRYSIDE',
    name: 'Countryside Village',
    koreanName: '시골 마을',
    subtitle: '깊은 유대와 정체된 지경',
    description: '적은 유입이지만 한 사람과의 관계가 깊게 맺어집니다. 영적 침체를 깨우고 새로운 지경으로의 분립 파송이 핵심입니다.',
    populationIndicator: '●●○○○',
    mobilityIndicator: '●○○○○',
    crisisSummary: '침체 · 폐쇄성',
    populationDensity: 0.4,
    populationSpawnRate: 0.6,
    mobility: 0.5,
    averageStayTime: 2.0,
    openness: 0.45,
    ageProfile: {
      young: 0.15,
      adult: 0.45,
      senior: 0.4,
    },
    driftWeights: {
      deception: 0.15,
      division: 0.25,
      burnout: 0.2,
      apathy: 0.4, // 침체 위기 가중치 높음
    },
    zones: [
      {
        id: 'VILLAGE',
        name: '마을 안길',
        englishName: 'Village Heart',
        relX: 0.5,
        relY: 0.5,
        relRadius: 0.35,
        influence: {
          speedMultiplier: 0.8,
          questionNeedMultiplier: 0.7,
          careMultiplier: 1.3,
          relationshipMultiplier: 1.4,
        },
      },
      {
        id: 'MARKET',
        name: '오일장 장터',
        englishName: 'Local Market',
        relX: 0.25,
        relY: 0.3,
        relRadius: 0.22,
        influence: {
          speedMultiplier: 1.1,
          questionNeedMultiplier: 1.1,
          careMultiplier: 0.9,
          relationshipMultiplier: 1.2,
        },
      },
      {
        id: 'SCHOOL',
        name: '작은 배움터',
        englishName: 'Old School',
        relX: 0.75,
        relY: 0.28,
        relRadius: 0.22,
        influence: {
          speedMultiplier: 0.9,
          questionNeedMultiplier: 1.2,
          careMultiplier: 1.1,
          relationshipMultiplier: 1.1,
        },
      },
      {
        id: 'OUTSKIRTS',
        name: '외곽 과수원길',
        englishName: 'Rural Outskirts',
        relX: 0.3,
        relY: 0.75,
        relRadius: 0.25,
        influence: {
          speedMultiplier: 0.7,
          questionNeedMultiplier: 0.6,
          careMultiplier: 0.8,
          relationshipMultiplier: 0.7,
        },
      },
    ],
  },

  CAMPUS: {
    id: 'CAMPUS',
    name: 'University Campus',
    koreanName: '대학가',
    subtitle: '빠른 유입과 거센 돌봄 과부하',
    description: '청년들의 끊임없는 탐색과 질문이 쏟아집니다. 폭발적인 유입으로 목자의 돌봄 수용력이 시험받으며, 거짓 사상(혼란)에 주의해야 합니다.',
    populationIndicator: '●●●●○',
    mobilityIndicator: '●●●●●',
    crisisSummary: '혼란 · 이탈',
    populationDensity: 0.85,
    populationSpawnRate: 1.5,
    mobility: 1.3,
    averageStayTime: 0.75,
    openness: 0.85,
    ageProfile: {
      young: 0.82,
      adult: 0.15,
      senior: 0.03,
    },
    driftWeights: {
      deception: 0.45, // 혼란/왜곡 가중치 높음
      division: 0.25,
      burnout: 0.15,
      apathy: 0.15,
    },
    zones: [
      {
        id: 'CAMPUS_PLAZA',
        name: '캠퍼스 중앙광장',
        englishName: 'Central Plaza',
        relX: 0.5,
        relY: 0.45,
        relRadius: 0.32,
        influence: {
          speedMultiplier: 1.2,
          questionNeedMultiplier: 1.6,
          careMultiplier: 1.0,
          relationshipMultiplier: 1.3,
        },
      },
      {
        id: 'DORM',
        name: '기숙사 타운',
        englishName: 'Dormitory Area',
        relX: 0.25,
        relY: 0.68,
        relRadius: 0.25,
        influence: {
          speedMultiplier: 0.85,
          questionNeedMultiplier: 0.9,
          careMultiplier: 1.4,
          relationshipMultiplier: 1.5,
        },
      },
      {
        id: 'STATION',
        name: '대학역 환승구',
        englishName: 'Metro Hub',
        relX: 0.78,
        relY: 0.35,
        relRadius: 0.26,
        influence: {
          speedMultiplier: 1.5,
          questionNeedMultiplier: 1.3,
          careMultiplier: 0.6,
          relationshipMultiplier: 0.8,
        },
      },
      {
        id: 'CAFE',
        name: '청년 카페거리',
        englishName: 'Cafe Alley',
        relX: 0.72,
        relY: 0.72,
        relRadius: 0.24,
        influence: {
          speedMultiplier: 0.9,
          questionNeedMultiplier: 1.2,
          careMultiplier: 1.2,
          relationshipMultiplier: 1.4,
        },
      },
    ],
  },

  DOWNTOWN: {
    id: 'DOWNTOWN',
    name: 'Metropolitan Downtown',
    koreanName: '도심지',
    subtitle: '치열한 삶의 현장과 극심한 소진',
    description: '수많은 인파가 바쁘게 스쳐 지나가며 영적 고갈과 무관심이 만연합니다. 기도를 통한 은혜의 품 확보와 목회적 쉼이 절실합니다.',
    populationIndicator: '●●●●●',
    mobilityIndicator: '●●●●●',
    crisisSummary: '소진 · 무관심',
    populationDensity: 1.0,
    populationSpawnRate: 1.3,
    mobility: 1.1,
    averageStayTime: 0.85,
    openness: 0.65,
    ageProfile: {
      young: 0.3,
      adult: 0.6,
      senior: 0.1,
    },
    driftWeights: {
      deception: 0.15,
      division: 0.2,
      burnout: 0.45, // 소진 가중치 매우 높음
      apathy: 0.2,
    },
    zones: [
      {
        id: 'OFFICE',
        name: '비즈니스 빌딩가',
        englishName: 'Financial Center',
        relX: 0.48,
        relY: 0.42,
        relRadius: 0.33,
        influence: {
          speedMultiplier: 1.3,
          questionNeedMultiplier: 0.9,
          careMultiplier: 0.8,
          relationshipMultiplier: 0.8,
        },
      },
      {
        id: 'STATION',
        name: '광역 중앙역',
        englishName: 'Central Station',
        relX: 0.22,
        relY: 0.32,
        relRadius: 0.25,
        influence: {
          speedMultiplier: 1.6,
          questionNeedMultiplier: 1.0,
          careMultiplier: 0.5,
          relationshipMultiplier: 0.7,
        },
      },
      {
        id: 'RESIDENTIAL',
        name: '도심 주거단지',
        englishName: 'Residential Sector',
        relX: 0.3,
        relY: 0.75,
        relRadius: 0.26,
        influence: {
          speedMultiplier: 0.8,
          questionNeedMultiplier: 1.0,
          careMultiplier: 1.3,
          relationshipMultiplier: 1.3,
        },
      },
      {
        id: 'COMMERCIAL',
        name: '상업 문화지구',
        englishName: 'Urban Mall',
        relX: 0.76,
        relY: 0.62,
        relRadius: 0.26,
        influence: {
          speedMultiplier: 1.2,
          questionNeedMultiplier: 1.1,
          careMultiplier: 0.9,
          relationshipMultiplier: 1.0,
        },
      },
    ],
  },
};
